# Generated by Django 4.2.16 on 2024-11-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='название изображения')),
                ('image', models.ImageField(upload_to='media/slider_images/', verbose_name='изображение')),
                ('description', models.TextField(blank=True, verbose_name='описание изображения')),
            ],
        ),
    ]
